### ISSUE TITLE
Display reminder if all the slots in either dose-1 or dose-2 are zero.

### ISSUE THREAD

**Issue by sanskar10100** [saumy0010/vaccine-slot-alert#1]
I mean, what if I wanna set a reminder for dose 1 here?

![image](https://user-images.githubusercontent.com/22092047/127338938-260d5bfc-539f-4d86-91d5-7dd32006925c.png)

**Comment by saumy0010** [comment]
Thank you for your useful suggestion 
Now you can check the update
